# Generated by Django 4.1.3 on 2023-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(db_column='Comment_text')),
                ('comment_time', models.DateTimeField(db_column='Comment_time')),
                ('parent_comment_id', models.IntegerField(db_column='Parent_comment_id')),
            ],
            options={
                'db_table': 'Comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('dislike_id', models.AutoField(db_column='Dislike_id', primary_key=True, serialize=False)),
                ('dislike_time', models.DateTimeField(db_column='Dislike_time')),
            ],
            options={
                'db_table': 'Dislikes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.AutoField(db_column='Like_id', primary_key=True, serialize=False)),
                ('like_time', models.DateTimeField(db_column='Like_time')),
            ],
            options={
                'db_table': 'Likes',
                'managed': False,
            },
        ),
    ]
