# Generated by Django 4.1.3 on 2023-02-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='likes',
            table='likes',
        ),
    ]
