# Generated by Django 4.1.3 on 2023-02-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_comment_table_alter_likes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dislikes',
            table='dislikes',
        ),
    ]
