# Generated by Django 4.1.3 on 2023-02-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='playlists',
            table='playlists',
        ),
        migrations.AlterModelTable(
            name='videoanalytics',
            table='videoanalytics',
        ),
        migrations.AlterModelTable(
            name='videodetails',
            table='videodetails',
        ),
        migrations.AlterModelTable(
            name='viewerinformation',
            table='viewerinformation',
        ),
        migrations.AlterModelTable(
            name='views',
            table='views',
        ),
    ]
